### ISSUE TITLE
`index()` treats both numbers with and without units as the same value.

### ISSUE THREAD

**Issue by oscarmarcelo** [sass/ruby-sass#106]
Ruby Sass `index()` treats both numbers with and without units as the same value.
For example: `1 == 1px`.

## input.scss

```scss
test {
  content: inspect(index(true 1, 1px));
}
```

## Actual results

ruby sass 3.7.2
```css
test {
  content: 2; }
```

## Expected result

dart sass 1.6.2
```css
test {
  content: null; }
```

LibSass also has the same error. sass/libsass#2810

[libsass 3.5.2][1]
```css
test {
  content: 2; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY2FzZTogaW5zcGVjdChpbmRleCh0cnVlIDEsIDFweCkpOwp9
