### ISSUE TITLE
Extending with & and pseudo class omits pseudo class 

### ISSUE THREAD

**Issue by andraaspar** [sass/ruby-sass#109]
Using `"sass": "1.17.0"` in Node `v10.15.0` on Windows 10:

# Input
```SCSS
.foo {
  &,
  &:visited {
    color: red;
  }
}

.bar {
  @extend .foo;
}

```

# Expected result
```CSS
.foo, .bar, .foo:visited, .bar:visited {
  color: red;
}
```

# Actual result
```CSS
.foo, .bar, .foo:visited {
  color: red;
}
```

**Comment by andraaspar** [comment]
# Workaround

```SCSS
@mixin self-and($ALSO) {
  // Workaround to https://github.com/sass/ruby-sass/issues/109
  & {
    @content;
  }
  #{$ALSO} {
    @content;
  }
}

.foo {
  @include self-and('&:visited') {
    color: red;
  }
}

.bar {
  @extend .foo;
}
```

# Result

```CSS
.foo, .bar {
  color: red;
}
.foo:visited, .bar:visited {
  color: red;
}
```

Suboptimal, but correct.
