### ISSUE TITLE
:has() pseudo-class doesn't compile correctly when nested

### ISSUE THREAD

**Issue by kaelig** [sass/ruby-sass#110]
The [`:has` pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) doesn't get compiled correctly when nested, see https://www.sassmeister.com/gist/a3dc4d7d09c7434bffb7dce3078e7836

### Source

```scss
.foo > p:not(:has(> img)) {
  max-width: 42rem;
}

.foo {
  > p:not(:has(> img)) {
    max-width: 42rem;
  }
}
```

### Expected

```css
.foo > p:not(:has(> img)) {
  max-width: 42rem;
}

.foo > p:not(:has(> img)) {
  max-width: 42rem;
}
```

### Actual

```css
.foo > p:not(:has(> img)) {
  max-width: 42rem;
}

.foo > p {
  max-width: 42rem;
}
```
